name: Execute Postman tests
on:
  push:
  workflow_dispatch: 
   
jobs: 
  postman-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install newman
        run: npm install -g newman
      
      - name: install html extra reporter
        run: npm install -g newman-reporter-htmlextra

      - name: run postman test
        use: newman run postman/collection-exo-3.json -r cli.htmlextra

      - name: publish html reporter
        uses: actions/upload-artifact@v4
        with:
          name: newman-reporter
          path: newman